title: Img3Sum
email: kaoara@naver.com
description: >- # this means to ignore newlines until "baseurl:"
  Open-source project that supports translating, summarizing and converting images to text.

theme: minima

base_url: /ga_blog_img3sum

# Minima social links
github_username:  Lainshower

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/features.md
  - _pages/contact-us.md 

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
